PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX traces-geo: <http://purl.org/net/traces/dataset/geo/>
PREFIX sett: <http://purl.org/net/sett#>
PREFIX tsn: <http://purl.org/net/tsn#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX ign:<http://data.ign.fr/def/geometrie#>
	

SELECT  ?name ?coordinates
WHERE {
  ?municipality a sett:TerritorialUnit;
                tsn:hasName ?name ;
                tsn:hasIdentifier ?code ;
                sett:country traces-geo:France ;
                owl:sameAs ?officialOntology .
                 
  #FILTER (?name = "Abondance")
  SERVICE <https://rdf.insee.fr/sparql>
  { 
  	?officialOntology owl:sameAs ?geofla .   
  } 
  
  SERVICE <http://data.ign.fr/id/sparql>
    {
          ?geofla ign:geometry ?o .
		  ?o geo:asWKT ?coordinates .
    } 
    
  FILTER(!STRSTARTS(STR(?geofla), "http://id.insee.fr"))
  
}
LIMIT 10

