PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX traces-geo: <http://purl.org/net/traces/dataset/geo/>
PREFIX sett: <http://purl.org/net/sett#>
PREFIX tsn: <http://purl.org/net/tsn#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT  ?population ?predicate ?information
WHERE {
  ?municipality a sett:TerritorialUnit;
                tsn:hasName ?name ;
                sett:country traces-geo:France ;
                owl:sameAs ?officialOntology .
  FILTER (?name = "Abondance")
  SERVICE <https://rdf.insee.fr/sparql>
  { 
  	?officialOntology <http://rdf.insee.fr/def/demo#population> ?population . 
    ?population ?predicate ?information .
    FILTER ( ?predicate != rdf:type)
  } 
  
}





